services:
  back:
    build:
      context: ./back
    ports:
      - 8080:8080
    environment:
      MYSQL_USER: usertest
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: Gastou84!
      MYSQL_PASSWORD: Password
      DATABASE_URL: jdbc:mysql://host.docker.internal:3306/test


  

  front:
    build:
      context: ./front
    depends_on:
      - back

